const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Flash,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Janela: 0},
	{Solid: 0},
	{Suporte: 0},
	{Caixas: 0},
	{Porta: 0},
	{Sensor_solido: 0},
	{Jogador: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Sprite: 0},
	{Keyboard: 0},
	{Direcao: 0},
	{Flash: 0},
	{Sprite2: 0},
	{Sensor_direita: 0},
	{Sensor_esquerda: 0},
	{direcao: 0},
	{Back: 0},
	{sendor_direita: 0},
	{sendor_esquerda: 0},
	{Sprite3: 0},
	{Audio: 0},
	{Menu: 0},
	{Button: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Vidas: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Janela: class extends self.ISpriteInstance {},
	Suporte: class extends self.ISpriteInstance {},
	Caixas: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Sensor_solido: class extends self.ISpriteInstance {},
	Jogador: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sensor_direita: class extends self.ISpriteInstance {},
	Sensor_esquerda: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	sendor_direita: class extends self.ISpriteInstance {},
	sendor_esquerda: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Menu: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}